"""Sonarr Tag pydantic schema.

Used for ``arrconf-managed`` tag reconciliation (D-02). Source: Sonarr
OpenAPI #/components/schemas/TagResource — only ``id`` and ``label``.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Tag(BaseModel):
    """A Sonarr tag."""

    model_config = ConfigDict(extra="allow")  # API-parsing model — forward-compat
    id: int | None = Field(default=None, exclude=True, description="Tag ID (generated by Sonarr).")
    label: str = Field(description="Tag display name (matching key, e.g., 'arrconf-managed').")
