"""Phase 33 configarr.yml generator (CFGARR-01..04).

Pure-function module: IntentConfig → committed configarr.yml content string.

Design decisions (from orchestrator pre-resolution):
- D-33-04 Option B: profile names in intent.yml stay as ``general``/``anime``/``family``
  (enum in resources/categories.py unchanged, zero test churn). The generator maps
  to configarr names at emit time via ``_PROFILE_NAME_MAP``. ``profile_definitions``
  is keyed by the configarr names (MULTi.VF/Anime/Family).
- D-33-05: only profiles *referenced* by categories of the matching kind are emitted.
  No dead profiles (e.g. Anime profile never appears in radarr if no anime movie category).
- D-33-06 / CFGARR-02: custom_formats grouped by trash_ids tuple (Option A). All profiles
  sharing the same trash_ids group appear in a single assign_scores_to list.
- D-33-07: everything in ``IntentConfig.configarr`` except quality_profiles/custom_formats
  is emitted verbatim (pass-through). The generator deep-copies the skeleton dict before
  injection so the IntentConfig model is never mutated.
- D-33-08: the configarr emitter in generate() is unconditional — intent always carries
  the configarr: block.
- ADR-5 (CFGARR-04): this module is STRICTLY pure. No httpx, no ArrApiClient, no reconcile
  import. ``test_no_api_calls_adr5`` asserts this at both source and runtime levels.
- CFGARR-03 / T-33-01: api_key emitted as bare ``!env VAR`` tag (never an expanded secret).
  ruyaml.YAML(typ="safe").dump() would quote the string ``!env SONARR_API_KEY``; a regex
  post-processor converts any ``api_key: '!env VAR'`` pattern back to a bare YAML tag.
"""

from __future__ import annotations

import copy
import io
import re
from typing import Any, Final

from arrconf.generators.intent import sort_dict
from arrconf.intent_config import IntentConfig

_CONFIGARR_HEADER: Final[str] = (
    "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"
    "# Source: charts/arr-stack/files/intent.yml\n"
    "# Run: cd tools/arrconf && uv run arrconf generate"
    " --intent ../../charts/arr-stack/files/intent.yml"
    " --output-dir ../../charts/arr-stack/files/\n"
)

# D-33-04 Option B: intent.yml enum values → configarr profile names.
# Keeps Category.profile as "general"/"anime"/"family" (zero test churn).
_PROFILE_NAME_MAP: Final[dict[str, str]] = {
    "general": "MULTi.VF",
    "anime": "Anime",
    "family": "Family",
}

# Maps MediaCategory.kind to the configarr instance key.
_KIND_TO_INSTANCE: Final[dict[str, str]] = {"series": "sonarr", "movies": "radarr"}


def generate_configarr_yml(intent_cfg: IntentConfig) -> str:
    """Pure function: IntentConfig -> configarr.yml content string.

    Algorithm:
    1. Deep-copy the pass-through skeleton (``IntentConfig.configarr``) so injection
       never mutates the model.
    2. Route profiles per instance (D-33-05): collect only the configarr profile names
       referenced by categories whose ``kind`` matches the instance (series→sonarr,
       movies→radarr). Profiles not referenced by any category are NOT emitted.
    3. quality_profiles (CFGARR-01): for each referenced profile name, emit
       ``{"name": name, **profile_definitions[name].body}``.
    4. custom_formats (CFGARR-02 / D-33-06 Option A): for the referenced profiles of
       this instance, group CustomFormatRef entries by ``trash_ids`` tuple. For each
       distinct group, emit one entry with an ``assign_scores_to`` list; ``score`` is
       included only when the CustomFormatRef.score is not None.
    5. Serialize via ``ruyaml.YAML(typ="safe")`` + ``sort_dict`` for determinism.
       Prepend ``_CONFIGARR_HEADER``.
    6. Post-process: convert any ``api_key: '!env VAR'`` or ``api_key: "!env VAR"``
       back to bare ``api_key: !env VAR`` (CFGARR-03 / T-33-01 — never an expanded
       secret in the committed file).

    Security: ruyaml.dump() handles value escaping; no f-string interpolation of
    raw user values (T-33-03 STRIDE mitigation, mirrors T-32-04).

    Determinism: sort_dict guarantees byte-reproducible output regardless of dict
    insertion order. The function is pure (same intent → same string, SC#4).
    """
    from ruyaml import YAML

    # Step 1 — deep-copy pass-through skeleton.
    doc: dict[str, Any] = copy.deepcopy(dict(intent_cfg.configarr))

    # Steps 2-4 — per-instance profile routing + injection.
    for kind, instance in _KIND_TO_INSTANCE.items():
        # D-33-05: only profiles referenced by categories of matching kind.
        referenced = sorted(
            {
                _PROFILE_NAME_MAP[c.profile]
                for c in intent_cfg.categories
                if c.kind == kind and c.profile in _PROFILE_NAME_MAP
            }
        )
        if not referenced:
            continue

        # Ensure the instance path exists in the doc (pass-through may omit it).
        doc.setdefault(instance, {})
        doc[instance].setdefault("main", {})

        # Step 3 — quality_profiles (CFGARR-01).
        quality_profiles: list[dict[str, Any]] = []
        for profile_name in referenced:
            if profile_name not in intent_cfg.profile_definitions:
                continue
            pdef = intent_cfg.profile_definitions[profile_name]
            entry: dict[str, Any] = {"name": profile_name, **pdef.body}
            quality_profiles.append(entry)
        doc[instance]["main"]["quality_profiles"] = quality_profiles

        # Step 4 — custom_formats (CFGARR-02 / D-33-06 Option A).
        # Group by trash_ids tuple across the referenced profiles. Iterate profiles
        # in sorted order so assign_scores_to entries are deterministically ordered.
        groups: dict[tuple[str, ...], list[dict[str, Any]]] = {}
        for profile_name in referenced:
            if profile_name not in intent_cfg.profile_definitions:
                continue
            for cf_ref in intent_cfg.profile_definitions[profile_name].custom_formats:
                key = tuple(sorted(cf_ref.trash_ids))
                if key not in groups:
                    groups[key] = []
                assign_entry: dict[str, Any] = {"name": profile_name}
                if cf_ref.score is not None:
                    assign_entry["score"] = cf_ref.score
                groups[key].append(assign_entry)

        custom_formats: list[dict[str, Any]] = []
        for trash_ids_key, assign_scores_to in groups.items():
            custom_formats.append(
                {
                    "trash_ids": list(trash_ids_key),
                    "assign_scores_to": assign_scores_to,
                }
            )
        doc[instance]["main"]["custom_formats"] = custom_formats

    # Step 5 — serialize.
    yaml = YAML(typ="safe")
    yaml.default_flow_style = False
    stream = io.StringIO()
    yaml.dump(sort_dict(doc), stream)
    rendered = _CONFIGARR_HEADER + stream.getvalue()

    # Step 6 — reconstruct !env tags (CFGARR-03 / T-33-01).
    # ruyaml.YAML(typ="safe") serializes "!env SONARR_API_KEY" as a quoted string.
    # Configarr requires a bare YAML tag: api_key: !env SONARR_API_KEY.
    rendered = re.sub(
        r"(?m)^(\s*api_key:\s*)['\"]!env (\w+)['\"]\s*$",
        r"\1!env \2",
        rendered,
    )

    return rendered
