"""Phase 28 generate-foundation — cross-seed config.js generator (INTENT-02 / XSEED-02).

Pure-function module: CrossSeedConfig → committed config.js content string.
This is the P28 D-03 proving slice: emit novel JS literal format from the
generate framework, de-risking Phase 30 (full cross-seed reconciler).

Phase 32 (CATMIG-02): adds generate_arrconf_yml — IntentConfig.apps pass-through
emitter. Determinism by construction via _sort_dict recursive key sorter (SC#4).

Key invariants:
- All generators are pure functions (no I/O, no file access, no httpx).
- generate_cross_seed determinism: json.dumps(sort_keys=True).
- generate_arrconf_yml determinism: _sort_dict before ruyaml dump (SC#4).
- Security: json.dumps / ruyaml handle value escaping — no f-string interpolation
  of raw user values (T-28-04 / T-28-05 / T-32-04 STRIDE mitigations).
"""

from __future__ import annotations

import io
import json
from typing import Any, Final

from arrconf.intent_config import CrossSeedConfig, IntentConfig, QbitManageConfig
from arrconf.resources.qbittorrent.category import Category as QbitCategory

_HEADER: Final[str] = "// GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"


def generate_cross_seed(cfg: CrossSeedConfig) -> str:
    """Pure function: CrossSeedConfig → committed config.js content string.

    Determinism guarantee: json.dumps(sort_keys=True) produces byte-identical
    output across runs regardless of pydantic field insertion order.

    This is the P28 proving slice (D-03): validates that the generate framework
    supports JS literal emission (CommonJS module.exports), not just YAML.
    Phase 30 will wire the CLI generate command to write this to disk.

    Empty list fields are omitted from the JS object (operator intent: unset ≠
    empty array). linkType and action are always present (they carry defaults).
    """
    data: dict[str, object] = {}
    if cfg.torznab:
        data["torznab"] = cfg.torznab
    if cfg.torrent_clients:
        data["torrentClients"] = cfg.torrent_clients
    if cfg.link_dirs:
        data["linkDirs"] = cfg.link_dirs
    if cfg.data_dirs:
        data["dataDirs"] = cfg.data_dirs
    if cfg.search_cadence is not None:
        data["searchCadence"] = cfg.search_cadence
    if cfg.exclude_recent_search is not None:
        data["excludeRecentSearch"] = cfg.exclude_recent_search
    if cfg.exclude_older is not None:
        data["excludeOlder"] = cfg.exclude_older
    if cfg.skip_recheck is not None:
        data["skipRecheck"] = cfg.skip_recheck
    if cfg.max_data_depth is not None:
        data["maxDataDepth"] = cfg.max_data_depth
    data["linkType"] = cfg.link_type
    data["action"] = cfg.action
    body = json.dumps(data, indent="\t", sort_keys=True, ensure_ascii=False)
    return f"{_HEADER}module.exports = {body};\n"


_QBM_HEADER: Final[str] = (
    "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"
)


def generate_qbit_manage(cfg: QbitManageConfig, categories: list[QbitCategory]) -> str:
    """Pure function: (QbitManageConfig, qBit categories) → config.yml content string.

    Structured against the real qbit_manage v4.6.6 schema (verified against the
    image's config.yml.sample):
    - commands:  operation toggles. cat_update: false (QBM-02 — arrconf is sole
      category owner, no second writer). share_limits / tag_update /
      tag_tracker_error enabled; rem_orphaned / rem_unregistered from cfg;
      tag_nohardlinks / recheck off (not configured).
    - qbt:  connection (host + !ENV creds).
    - settings:  minimal tuning only — qbit_manage auto-fills missing sub-attributes
      with defaults. Operation toggles live in commands:, NOT here.
    - cat:  <name>: <save_path> for every arrconf category. MANDATORY non-empty
      section in v4.6.6 ("Category section is not completed and is mandatory").
      cat_update:false (above) is the no-writer guard; cat only lets qbit_manage
      *know* the categories for filtering — it never mutates them.
    - tracker:  <keyword>: {tag}. MANDATORY non-empty section ("Tracker section is
      not completed and is mandatory"). The key is `tracker:`, NOT `tracker_tags:`.
    - share_limits:  per-group ratio/seeding policy (top-level).
    - recyclebin:  top-level section (NOT nested under settings).
    - orphaned:  emitted only when rem_orphaned is enabled.

    The categories are sourced from arrconf.yml (the hand-edited owner), passed in
    by the `generate` CLI — keeps this function pure (no I/O) while mirroring the
    same `<name> → /data/torrents/<name>` mapping as generate_qbit_categories.

    Security: !ENV tags emitted as YAML literal strings via string construction —
    ruyaml.dump() cannot produce '!ENV VAR_NAME' tagged scalars without a custom
    representer (Pitfall 1 in RESEARCH.md — avoided by string construction).
    Determinism: explicit section/key order; categories sorted by name.
    """
    rem_orphaned = "true" if cfg.rem_orphaned else "false"
    rem_unregistered = "true" if cfg.rem_unregistered else "false"
    lines: list[str] = [_QBM_HEADER]
    # commands: drive which operations run. cat_update HARD false (QBM-02).
    lines += [
        "commands:",
        "  dry_run: false",
        "  recheck: false",
        "  cat_update: false            # QBM-02: arrconf is sole category owner",
        "  tag_update: true",
        f"  rem_unregistered: {rem_unregistered}",
        "  tag_tracker_error: true",
        f"  rem_orphaned: {rem_orphaned}",
        "  tag_nohardlinks: false       # nohardlinks not configured in intent",
        "  share_limits: true",
        "  skip_qb_version_check: false",
        "  skip_cleanup: false",
        "",
    ]
    lines += [
        "qbt:",
        f"  host: {cfg.qbt_host}",
        "  user: !ENV QBT_USER",
        "  pass: !ENV QBT_PASS",
        "",
    ]
    # Minimal settings — qbit_manage auto-fills the rest with defaults.
    lines += [
        "settings:",
        "  force_auto_tmm: false",
        "",
    ]
    # MANDATORY: directory.root_dir (qbit_manage errors "directory attribute not
    # found" without it). root_dir is the qBit-side torrents root — matches the
    # cat save_paths (/data/torrents/<name>). recycle_bin lives under it.
    lines += [
        "directory:",
        "  root_dir: /data/torrents",
        "  recycle_bin: /data/torrents/.RecycleBin",
        "",
    ]
    # MANDATORY: cat populated (cat_update:false above keeps arrconf the owner).
    lines.append("cat:")
    for cat in sorted(categories, key=lambda c: c.name):
        lines.append(f"  {cat.name}: {cat.savePath}")
    lines.append("")
    # MANDATORY: tracker section (key is `tracker:`, NOT `tracker_tags:`).
    lines.append("tracker:")
    for entry in cfg.tracker_tags:
        lines += [f"  {entry.keyword}:", f"    tag: {entry.tag}"]
    lines += ["  other:", "    tag: public", ""]
    lines.append("share_limits:")
    for grp in sorted(cfg.share_limits, key=lambda g: g.priority):
        lines += [
            f"  {grp.name}:",
            f"    priority: {grp.priority}",
            "    include_all_tags:",
            f"      - {grp.tracker_tag}",
            f"    max_ratio: {grp.max_ratio}",
            f"    max_seeding_time: {grp.max_seeding_time}",
            f"    min_seeding_time: {grp.min_seeding_time}",
            f"    cleanup: {'true' if grp.cleanup else 'false'}",
        ]
    # Catch-all group (lowest priority, no tag filter → matches remaining torrents).
    lines += [
        "  default:",
        "    priority: 999",
        "    max_ratio: 2.0",
        "    max_seeding_time: 10080",
        "    min_seeding_time: 0",
        "    cleanup: false",
        "",
    ]
    # recyclebin is a TOP-LEVEL section in v4.6.6 (not nested under settings).
    lines += [
        "recyclebin:",
        "  enabled: true",
        f"  empty_after_x_days: {cfg.recyclebin_days}",
        "  save_torrents: false",
        "  split_by_category: false",
        "",
    ]
    if cfg.rem_orphaned:
        lines += [
            "orphaned:",
            "  empty_after_x_days: 30",
            "  exclude_patterns: []",
            "",
        ]
    return "\n".join(lines)


_ARRCONF_HEADER: Final[str] = (
    "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"
    "# Source: charts/arr-stack/files/intent.yml\n"
    "# Run: cd tools/arrconf && uv run arrconf generate"
    " --intent ../../charts/arr-stack/files/intent.yml"
    " --output-dir ../../charts/arr-stack/files/\n"
)


def sort_dict(d: Any) -> Any:
    """Recursively sort dict keys for deterministic YAML output (SC#4).

    Determinism by construction — does not rely on ruyaml insertion-order
    preservation or on a fixed parse order of intent.yml.

    Public (renamed from _sort_dict in Phase 33) so generators/configarr.py
    can import it directly — no duplication (orchestrator decision 2 / D-33).
    """
    if isinstance(d, dict):
        return {k: sort_dict(v) for k, v in sorted(d.items())}
    if isinstance(d, list):
        return [sort_dict(x) for x in d]
    return d


def generate_arrconf_yml(intent_cfg: IntentConfig) -> str:
    """Pure: IntentConfig -> arrconf.yml content (apps pass-through).

    Emits the GENERATED header then intent_cfg.apps dumped as deterministic
    YAML (keys recursively sorted via sort_dict). Categories-derived *arr
    resources are NOT stored here — they materialize at apply-time from
    intent_cfg.categories (Plan 01). The output validates against RootConfig
    (apply/diff load it). No I/O.
    """
    from ruyaml import YAML

    yaml = YAML(typ="safe")
    yaml.default_flow_style = False
    stream = io.StringIO()
    yaml.dump(sort_dict(dict(intent_cfg.apps)), stream)
    return _ARRCONF_HEADER + stream.getvalue()
