"""Phase 28 generate-foundation — cross-seed config.js generator (INTENT-02 / XSEED-02).

Pure-function module: CrossSeedConfig → committed config.js content string.
This is the P28 D-03 proving slice: emit novel JS literal format from the
generate framework, de-risking Phase 30 (full cross-seed reconciler).

Key invariants:
- generate_cross_seed is a pure function (no I/O, no file access, no httpx).
- Determinism guaranteed by json.dumps(sort_keys=True): byte-identical across runs.
- Empty list fields (torznab, torrent_clients, link_dirs) are omitted from output.
- link_type and action are ALWAYS emitted (non-empty defaults).
- Security: json.dumps handles all value escaping — no f-string interpolation of
  raw user values (T-28-04 / T-28-05 STRIDE mitigations).
"""

from __future__ import annotations

import json
from typing import Final

from arrconf.intent_config import CrossSeedConfig, QbitManageConfig
from arrconf.resources.qbittorrent.category import Category as QbitCategory

_HEADER: Final[str] = "// GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"


def generate_cross_seed(cfg: CrossSeedConfig) -> str:
    """Pure function: CrossSeedConfig → committed config.js content string.

    Determinism guarantee: json.dumps(sort_keys=True) produces byte-identical
    output across runs regardless of pydantic field insertion order.

    This is the P28 proving slice (D-03): validates that the generate framework
    supports JS literal emission (CommonJS module.exports), not just YAML.
    Phase 30 will wire the CLI generate command to write this to disk.

    Empty list fields are omitted from the JS object (operator intent: unset ≠
    empty array). linkType and action are always present (they carry defaults).
    """
    data: dict[str, object] = {}
    if cfg.torznab:
        data["torznab"] = cfg.torznab
    if cfg.torrent_clients:
        data["torrentClients"] = cfg.torrent_clients
    if cfg.link_dirs:
        data["linkDirs"] = cfg.link_dirs
    data["linkType"] = cfg.link_type
    data["action"] = cfg.action
    body = json.dumps(data, indent="\t", sort_keys=True, ensure_ascii=False)
    return f"{_HEADER}module.exports = {body};\n"


_QBM_HEADER: Final[str] = (
    "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"
)


def generate_qbit_manage(cfg: QbitManageConfig, categories: list[QbitCategory]) -> str:
    """Pure function: (QbitManageConfig, qBit categories) → config.yml content string.

    Structured against the real qbit_manage v4.6.6 schema (verified against the
    image's config.yml.sample):
    - commands:  operation toggles. cat_update: false (QBM-02 — arrconf is sole
      category owner, no second writer). share_limits / tag_update /
      tag_tracker_error enabled; rem_orphaned / rem_unregistered from cfg;
      tag_nohardlinks / recheck off (not configured).
    - qbt:  connection (host + !ENV creds).
    - settings:  minimal tuning only — qbit_manage auto-fills missing sub-attributes
      with defaults. Operation toggles live in commands:, NOT here.
    - cat:  <name>: <save_path> for every arrconf category. MANDATORY non-empty
      section in v4.6.6 ("Category section is not completed and is mandatory").
      cat_update:false (above) is the no-writer guard; cat only lets qbit_manage
      *know* the categories for filtering — it never mutates them.
    - tracker:  <keyword>: {tag}. MANDATORY non-empty section ("Tracker section is
      not completed and is mandatory"). The key is `tracker:`, NOT `tracker_tags:`.
    - share_limits:  per-group ratio/seeding policy (top-level).
    - recyclebin:  top-level section (NOT nested under settings).
    - orphaned:  emitted only when rem_orphaned is enabled.

    The categories are sourced from arrconf.yml (the hand-edited owner), passed in
    by the `generate` CLI — keeps this function pure (no I/O) while mirroring the
    same `<name> → /data/torrents/<name>` mapping as generate_qbit_categories.

    Security: !ENV tags emitted as YAML literal strings via string construction —
    ruyaml.dump() cannot produce '!ENV VAR_NAME' tagged scalars without a custom
    representer (Pitfall 1 in RESEARCH.md — avoided by string construction).
    Determinism: explicit section/key order; categories sorted by name.
    """
    rem_orphaned = "true" if cfg.rem_orphaned else "false"
    rem_unregistered = "true" if cfg.rem_unregistered else "false"
    lines: list[str] = [_QBM_HEADER]
    # commands: drive which operations run. cat_update HARD false (QBM-02).
    lines += [
        "commands:",
        "  dry_run: false",
        "  recheck: false",
        "  cat_update: false            # QBM-02: arrconf is sole category owner",
        "  tag_update: true",
        f"  rem_unregistered: {rem_unregistered}",
        "  tag_tracker_error: true",
        f"  rem_orphaned: {rem_orphaned}",
        "  tag_nohardlinks: false       # nohardlinks not configured in intent",
        "  share_limits: true",
        "  skip_qb_version_check: false",
        "  skip_cleanup: false",
        "",
    ]
    lines += [
        "qbt:",
        f"  host: {cfg.qbt_host}",
        "  user: !ENV QBT_USER",
        "  pass: !ENV QBT_PASS",
        "",
    ]
    # Minimal settings — qbit_manage auto-fills the rest with defaults.
    lines += [
        "settings:",
        "  force_auto_tmm: false",
        "",
    ]
    # MANDATORY: directory.root_dir (qbit_manage errors "directory attribute not
    # found" without it). root_dir is the qBit-side torrents root — matches the
    # cat save_paths (/data/torrents/<name>). recycle_bin lives under it.
    lines += [
        "directory:",
        "  root_dir: /data/torrents",
        "  recycle_bin: /data/torrents/.RecycleBin",
        "",
    ]
    # MANDATORY: cat populated (cat_update:false above keeps arrconf the owner).
    lines.append("cat:")
    for cat in sorted(categories, key=lambda c: c.name):
        lines.append(f"  {cat.name}: {cat.savePath}")
    lines.append("")
    # MANDATORY: tracker section (key is `tracker:`, NOT `tracker_tags:`).
    lines.append("tracker:")
    for entry in cfg.tracker_tags:
        lines += [f"  {entry.keyword}:", f"    tag: {entry.tag}"]
    lines += ["  other:", "    tag: public", ""]
    lines.append("share_limits:")
    for grp in sorted(cfg.share_limits, key=lambda g: g.priority):
        lines += [
            f"  {grp.name}:",
            f"    priority: {grp.priority}",
            "    include_all_tags:",
            f"      - {grp.tracker_tag}",
            f"    max_ratio: {grp.max_ratio}",
            f"    max_seeding_time: {grp.max_seeding_time}",
            f"    min_seeding_time: {grp.min_seeding_time}",
            f"    cleanup: {'true' if grp.cleanup else 'false'}",
        ]
    # Catch-all group (lowest priority, no tag filter → matches remaining torrents).
    lines += [
        "  default:",
        "    priority: 999",
        "    max_ratio: 2.0",
        "    max_seeding_time: 10080",
        "    min_seeding_time: 0",
        "    cleanup: false",
        "",
    ]
    # recyclebin is a TOP-LEVEL section in v4.6.6 (not nested under settings).
    lines += [
        "recyclebin:",
        "  enabled: true",
        f"  empty_after_x_days: {cfg.recyclebin_days}",
        "  save_torrents: false",
        "  split_by_category: false",
        "",
    ]
    if cfg.rem_orphaned:
        lines += [
            "orphaned:",
            "  empty_after_x_days: 30",
            "  exclude_patterns: []",
            "",
        ]
    return "\n".join(lines)
