"""Phase 28 generate-foundation — cross-seed config.js generator (INTENT-02 / XSEED-02).

Pure-function module: CrossSeedConfig → committed config.js content string.
This is the P28 D-03 proving slice: emit novel JS literal format from the
generate framework, de-risking Phase 30 (full cross-seed reconciler).

Key invariants:
- generate_cross_seed is a pure function (no I/O, no file access, no httpx).
- Determinism guaranteed by json.dumps(sort_keys=True): byte-identical across runs.
- Empty list fields (torznab, torrent_clients, link_dirs) are omitted from output.
- link_type and action are ALWAYS emitted (non-empty defaults).
- Security: json.dumps handles all value escaping — no f-string interpolation of
  raw user values (T-28-04 / T-28-05 STRIDE mitigations).
"""

from __future__ import annotations

import json
from typing import Final

from arrconf.intent_config import CrossSeedConfig, QbitManageConfig

_HEADER: Final[str] = "// GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"


def generate_cross_seed(cfg: CrossSeedConfig) -> str:
    """Pure function: CrossSeedConfig → committed config.js content string.

    Determinism guarantee: json.dumps(sort_keys=True) produces byte-identical
    output across runs regardless of pydantic field insertion order.

    This is the P28 proving slice (D-03): validates that the generate framework
    supports JS literal emission (CommonJS module.exports), not just YAML.
    Phase 30 will wire the CLI generate command to write this to disk.

    Empty list fields are omitted from the JS object (operator intent: unset ≠
    empty array). linkType and action are always present (they carry defaults).
    """
    data: dict[str, object] = {}
    if cfg.torznab:
        data["torznab"] = cfg.torznab
    if cfg.torrent_clients:
        data["torrentClients"] = cfg.torrent_clients
    if cfg.link_dirs:
        data["linkDirs"] = cfg.link_dirs
    data["linkType"] = cfg.link_type
    data["action"] = cfg.action
    body = json.dumps(data, indent="\t", sort_keys=True, ensure_ascii=False)
    return f"{_HEADER}module.exports = {body};\n"


_QBM_HEADER: Final[str] = (
    "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND\n"
)


def generate_qbit_manage(cfg: QbitManageConfig) -> str:
    """Pure function: QbitManageConfig → committed config.yml content string.

    Key invariants enforced unconditionally (QBM-02/D-03/D-04):
    - cat_update: false  (never touches qBit categories)
    - cat: {}            (empty — no category management)
    - tag_nohardlinks: true (safe observability tag)
    - rem_orphaned / rem_unregistered: from cfg (default False)
    - recyclebin: enabled: true, empty_after_x_days from cfg

    Security: !ENV tags emitted as YAML literal strings via string construction —
    ruyaml.dump() cannot produce '!ENV VAR_NAME' tagged scalars without a custom
    representer (Pitfall 1 in RESEARCH.md — avoided by string construction).
    Determinism: explicit section/key order in the formatted string.
    """
    lines: list[str] = [_QBM_HEADER]
    lines += [
        "qbt:",
        f"  host: {cfg.qbt_host}",
        "  user: !ENV QBT_USER",
        "  pass: !ENV QBT_PASS",
        "",
    ]
    lines += [
        "settings:",
        "  force_auto_tmm: false",
        "  cat_update: false            # QBM-02: arrconf is sole category owner",
        "  tag_update: true",
        f"  rem_unregistered: {'true' if cfg.rem_unregistered else 'false'}",
        f"  rem_orphaned: {'true' if cfg.rem_orphaned else 'false'}",
        "  tag_nohardlinks: true        # D-03: observability only",
        "  skip_cleanup: false",
        "  dry_run: false",
        "  share_limits: true",
        "  recyclebin:",
        "    enabled: true",
        f"    empty_after_x_days: {cfg.recyclebin_days}",
        "    save_torrents: false",
        "",
    ]
    lines += ["cat: {}", ""]
    lines.append("tracker_tags:")
    for entry in cfg.tracker_tags:
        lines += [f"  {entry.keyword}:", f"    tag: {entry.tag}"]
    lines += ["  other:", "    tag: public", ""]
    lines.append("share_limits:")
    for grp in sorted(cfg.share_limits, key=lambda g: g.priority):
        lines += [
            f"  {grp.name}:",
            f"    priority: {grp.priority}",
            "    include_all_tags:",
            f"      - {grp.tracker_tag}",
            f"    max_ratio: {grp.max_ratio}",
            f"    max_seeding_time: {grp.max_seeding_time}",
            f"    min_seeding_time: {grp.min_seeding_time}",
            f"    cleanup: {'true' if grp.cleanup else 'false'}",
        ]
    # RESEARCH.md A1 — the default group omits include_all_tags, assumed to mean
    # "match all" (catch-all for untagged torrents). UNVERIFIED for qbit_manage
    # v4.6.6: verify post-deploy that untagged torrents actually match this group.
    lines += [
        "  default:",
        "    priority: 999",
        "    max_ratio: 2.0",
        "    max_seeding_time: 10080",
        "    min_seeding_time: 0",
        "    cleanup: false",
        "",
    ]
    lines += ["nohardlinks: {}", ""]
    return "\n".join(lines)
