apiVersion: v1
kind: ConfigMap
metadata:
  name: arrconf-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arr-stack.labels" . | nindent 4 }}
data:
  arrconf.yml: |
    {{- .Files.Get "files/arrconf.yml" | nindent 4 }}
  intent.yml: |
    {{- .Files.Get "files/intent.yml" | nindent 4 }}
