apiVersion: v1
kind: ConfigMap
metadata:
  name: cross-seed-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arr-stack.labels" . | nindent 4 }}
data:
  config.js: |
    {{- .Files.Get "files/cross-seed/config.js" | nindent 4 }}
