// GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND
module.exports = {
	"action": "inject",
	"dataDirs": [
		"/media/films",
		"/media/films-enfants",
		"/media/films-animation-enfants",
		"/media/films-zoe",
		"/media/nouveaux-films",
		"/media/series",
		"/media/series-emilie",
		"/media/series-garcons",
		"/media/series-thomas",
		"/media/series-zoe"
	],
	"excludeOlder": "2 weeks",
	"excludeRecentSearch": "3 days",
	"linkDirs": [
		"/media/.cross-seed"
	],
	"linkType": "hardlink",
	"maxDataDepth": 3,
	"searchCadence": "1 day",
	"skipRecheck": false,
	"torrentClients": [
		"qbittorrent:http://${QBT_USER}:${QBT_PASS}@qbittorrent.selfhost.svc.cluster.local:8080"
	],
	"torznab": [
		"http://prowlarr.selfhost.svc.cluster.local:9696/2/api?apikey=${PROWLARR_API_KEY}",
		"http://prowlarr.selfhost.svc.cluster.local:9696/5/api?apikey=${PROWLARR_API_KEY}",
		"http://prowlarr.selfhost.svc.cluster.local:9696/6/api?apikey=${PROWLARR_API_KEY}",
		"http://prowlarr.selfhost.svc.cluster.local:9696/7/api?apikey=${PROWLARR_API_KEY}"
	]
};
