// GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND
module.exports = {
	"action": "inject",
	"linkDirs": [
		"/data/torrents/cross-seed"
	],
	"linkType": "hardlink",
	"torrentClients": [
		"qbittorrent:http://admin:PLACEHOLDER@qbittorrent.selfhost.svc.cluster.local:8080"
	],
	"torznab": [
		"http://prowlarr.selfhost.svc.cluster.local:9696/1/api?apikey=PLACEHOLDER"
	]
};
