"""Unit tests for generate_qbit_manage() (Phase 31 QBM-01/QBM-02).

No HTTP — generator is pure Python.
"""

from __future__ import annotations

import io

from ruyaml import YAML

from arrconf.generators.intent import generate_qbit_manage
from arrconf.intent_config import QbitManageConfig, ShareLimitGroup

_yaml_safe = YAML(typ="safe")


def test_generate_qbit_manage_minimal() -> None:
    """Header present, output non-empty."""
    result = generate_qbit_manage(QbitManageConfig())
    assert result.startswith(
        "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND"
    )
    assert len(result) > 0


def test_generate_qbit_manage_deterministic() -> None:
    """Two calls with identical config produce byte-identical strings."""
    cfg = QbitManageConfig()
    assert generate_qbit_manage(cfg) == generate_qbit_manage(cfg)


def test_generate_qbit_manage_priority_order() -> None:
    """ShareLimitGroups are emitted sorted by priority ascending."""
    cfg = QbitManageConfig(
        share_limits=[
            ShareLimitGroup(name="high-prio", tracker_tag="tracker-a", priority=5),
            ShareLimitGroup(name="low-prio", tracker_tag="tracker-b", priority=1),
        ]
    )
    result = generate_qbit_manage(cfg)
    pos_low = result.index("low-prio:")
    pos_high = result.index("high-prio:")
    assert pos_low < pos_high, "priority=1 group must appear before priority=5 group"


def test_generate_qbit_manage_env_tags_literal() -> None:
    """!ENV tags emitted as literal unquoted YAML (Pitfall 1)."""
    result = generate_qbit_manage(QbitManageConfig())
    assert "  user: !ENV QBT_USER" in result
    assert "  pass: !ENV QBT_PASS" in result
    # Must NOT be quoted variants
    assert "user: '!ENV QBT_USER'" not in result
    assert 'user: "!ENV QBT_USER"' not in result
    assert "pass: '!ENV QBT_PASS'" not in result
    assert 'pass: "!ENV QBT_PASS"' not in result


def test_generate_qbit_manage_cat_update_false() -> None:
    """cat_update: false is always present, cat_update: true is never present."""
    result = generate_qbit_manage(QbitManageConfig())
    assert "cat_update: false" in result
    assert "cat_update: true" not in result


def test_generate_qbit_manage_cat_empty() -> None:
    """cat: {} is always present (QBM-02)."""
    result = generate_qbit_manage(QbitManageConfig())
    assert "cat: {}" in result


def test_generate_qbit_manage_rem_orphaned_default_false() -> None:
    """Default config emits rem_orphaned: false (D-04 opt-in)."""
    result = generate_qbit_manage(QbitManageConfig())
    assert "rem_orphaned: false" in result


def test_generate_qbit_manage_rem_orphaned_opt_in() -> None:
    """rem_orphaned: true when explicitly set in config."""
    result = generate_qbit_manage(QbitManageConfig(rem_orphaned=True))
    assert "rem_orphaned: true" in result


def test_generate_qbit_manage_recyclebin_days() -> None:
    """empty_after_x_days reflects recyclebin_days from config."""
    result = generate_qbit_manage(QbitManageConfig(recyclebin_days=7))
    assert "empty_after_x_days: 7" in result


def test_generate_qbit_manage_yaml_valid() -> None:
    """Non-qbt sections parse as valid YAML; cat_update is False and cat is empty (QBM-02)."""
    result = generate_qbit_manage(QbitManageConfig())
    # The qbt: block carries !ENV tags that yaml.safe_load cannot parse — strip it.
    kept = [
        line
        for line in result.splitlines()
        if "!ENV" not in line and line.strip() not in ("qbt:",) and not line.startswith("  host:")
    ]
    parsed = _yaml_safe.load(io.StringIO("\n".join(kept)))
    assert parsed["settings"]["cat_update"] is False
    assert parsed["cat"] == {}
