"""TDD tests for generate_arrconf_yml pure generator (Phase 32 Plan 02 / CATMIG-02).

RED phase: these tests must fail before the implementation is added.
GREEN phase: add generate_arrconf_yml to generators/intent.py to make them pass.

Invariants tested:
- GENERATED header is first line
- Body round-trips through RootConfig (loadable by apply/diff)
- No top-level categories: key (categories live in intent.yml only)
- Byte-identical determinism (calling twice yields same string)
- Keys in body are sorted regardless of input dict order
"""

from __future__ import annotations

import io

from ruyaml import YAML

from arrconf.generators.intent import _ARRCONF_HEADER, generate_arrconf_yml
from arrconf.intent_config import IntentConfig

# ---------------------------------------------------------------------------
# Fixture: minimal IntentConfig with apps but no categories
# ---------------------------------------------------------------------------


def _minimal_intent() -> IntentConfig:
    return IntentConfig.model_validate(
        {
            "apps": {
                "sonarr": {
                    "main": {
                        "base_url": "http://sonarr.example.com:8989",
                        "tags": {"prune": False},
                        "root_folders": {"prune": False},
                        "download_clients": {"prune": False},
                        "remote_path_mappings": {"prune": False},
                    }
                }
            }
        }
    )


def _reversed_key_intent() -> IntentConfig:
    """Intent with apps keys in reverse alphabetical order — tests key sorting."""
    return IntentConfig.model_validate(
        {
            "apps": {
                "zebra": {"nested": {"z": 1, "a": 2}},
                "alpha": {"nested": {"z": 1, "a": 2}},
            }
        }
    )


# ---------------------------------------------------------------------------
# Task 1 tests
# ---------------------------------------------------------------------------


def test_generate_arrconf_yml_starts_with_generated_header() -> None:
    """First line must be the _ARRCONF_HEADER (GENERATED by...) string."""
    intent = _minimal_intent()
    result = generate_arrconf_yml(intent)
    first_line = result.split("\n")[0]
    assert (
        first_line == "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND"
    ), f"First line mismatch: {first_line!r}"
    assert result.startswith(_ARRCONF_HEADER), "Output must start with _ARRCONF_HEADER constant"


def test_generate_arrconf_yml_body_round_trips_yaml() -> None:
    """The YAML body after the header parses to a dict equal to intent_cfg.apps."""
    intent = _minimal_intent()
    result = generate_arrconf_yml(intent)
    # Strip the header lines (count newlines in header)
    header_lines = _ARRCONF_HEADER.count("\n")
    body = "\n".join(result.split("\n")[header_lines:])
    yaml = YAML(typ="safe")
    parsed = yaml.load(io.StringIO(body))
    assert parsed == intent.apps, f"Round-trip failed: {parsed!r} != {intent.apps!r}"


def test_generate_arrconf_yml_no_categories_key() -> None:
    """Generated arrconf.yml must NOT contain a top-level categories: key."""
    intent = IntentConfig.model_validate(
        {
            "categories": [
                {
                    "name": "series",
                    "kind": "series",
                    "profile": "general",
                    "display": "Séries",
                    "base_path": "/media/series",
                }
            ],
            "apps": {
                "sonarr": {
                    "main": {
                        "base_url": "http://sonarr.example.com:8989",
                        "tags": {"prune": False},
                        "root_folders": {"prune": False},
                        "download_clients": {"prune": False},
                        "remote_path_mappings": {"prune": False},
                    }
                }
            },
        }
    )
    result = generate_arrconf_yml(intent)
    yaml = YAML(typ="safe")
    header_lines = _ARRCONF_HEADER.count("\n")
    body = "\n".join(result.split("\n")[header_lines:])
    parsed = yaml.load(io.StringIO(body)) or {}
    assert "categories" not in parsed, (
        "Generated arrconf.yml must NOT contain a top-level categories: key"
    )


def test_generate_arrconf_yml_byte_identical_determinism() -> None:
    """Calling generate_arrconf_yml twice on the same intent produces identical strings."""
    intent = _minimal_intent()
    result1 = generate_arrconf_yml(intent)
    result2 = generate_arrconf_yml(intent)
    assert result1 == result2, "generate_arrconf_yml is not deterministic"


def test_generate_arrconf_yml_keys_are_sorted() -> None:
    """Keys in the body are sorted regardless of input dict insertion order."""
    intent = _reversed_key_intent()
    result = generate_arrconf_yml(intent)
    yaml = YAML(typ="safe")
    header_lines = _ARRCONF_HEADER.count("\n")
    body = "\n".join(result.split("\n")[header_lines:])
    parsed = yaml.load(io.StringIO(body)) or {}
    top_keys = list(parsed.keys())
    assert top_keys == sorted(top_keys), f"Top-level keys are not sorted: {top_keys}"
    # Also check nested keys
    for v in parsed.values():
        if isinstance(v, dict):
            nested_keys = list(v.keys())
            assert nested_keys == sorted(nested_keys), f"Nested keys are not sorted: {nested_keys}"


def test_generate_arrconf_yml_rootconfig_round_trip() -> None:
    """Generated output (apps block) validates against RootConfig — loadable by apply/diff."""
    from arrconf.config import RootConfig

    intent = _minimal_intent()
    result = generate_arrconf_yml(intent)
    header_lines = _ARRCONF_HEADER.count("\n")
    body = "\n".join(result.split("\n")[header_lines:])
    yaml = YAML(typ="safe")
    parsed = yaml.load(io.StringIO(body)) or {}
    cfg = RootConfig.model_validate(parsed)
    assert isinstance(cfg, RootConfig), "Generated body did not round-trip through RootConfig"
