"""CLI tests for the ``arrconf generate`` subcommand (Phase 28 / INTENT-02 / INTENT-03).

Coverage:
- generate --help shows expected flags
- generate with valid intent.yml writes cross-seed/config.js, exits 0
- generate with missing intent.yml exits 2 (ConfigError)
- generate --check with committed content matching rendered exits 0
- generate --check with stale/absent committed content exits 1
"""

from __future__ import annotations

import shutil
from pathlib import Path

from typer.testing import CliRunner

from arrconf.__main__ import app

runner = CliRunner()

# Real committed arrconf.yml — source of the categories the qbit_manage generator
# mirrors into its cat: section. tests/ → arrconf/ → tools/ → repo root.
_ARRCONF_YML = Path(__file__).resolve().parents[3] / "charts/arr-stack/files/arrconf.yml"

_VALID_INTENT = """\
tools:
  cross_seed:
    torznab:
      - "http://prowlarr.test/1/api?apikey=PLACEHOLDER"
    torrent_clients: []
    link_dirs: []
    link_type: hardlink
    action: inject
sagas: []
"""


def test_generate_help_shows_flags() -> None:
    """generate --help must list --intent, --output-dir, --check."""
    result = runner.invoke(app, ["generate", "--help"])
    assert result.exit_code == 0
    assert "--intent" in result.stdout
    assert "--output-dir" in result.stdout
    assert "--check" in result.stdout


def test_generate_writes_config_js(tmp_path: Path) -> None:
    """bare generate with valid intent writes cross-seed/config.js, exits 0."""
    intent_file = tmp_path / "intent.yml"
    intent_file.write_text(_VALID_INTENT)
    out_dir = tmp_path / "out"
    out_dir.mkdir()

    result = runner.invoke(
        app,
        ["generate", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert result.exit_code == 0, f"Expected exit 0, got {result.exit_code}: {result.stdout}"
    config_js = out_dir / "cross-seed" / "config.js"
    assert config_js.exists(), "cross-seed/config.js was not written"
    content = config_js.read_text(encoding="utf-8")
    assert "// GENERATED by 'arrconf generate'" in content
    assert "module.exports = " in content


def test_generate_missing_intent_exits_2(tmp_path: Path) -> None:
    """generate with a nonexistent intent.yml exits 2 (ConfigError)."""
    missing = tmp_path / "nonexistent.yml"
    out_dir = tmp_path / "out"
    out_dir.mkdir()

    result = runner.invoke(
        app,
        ["generate", "--intent", str(missing), "--output-dir", str(out_dir)],
    )
    assert result.exit_code == 2, (
        f"Expected exit 2 (ConfigError / missing intent), got {result.exit_code}: {result.stdout}"
    )


def test_generate_check_exits_0_when_in_sync(tmp_path: Path) -> None:
    """generate --check exits 0 when committed file matches rendered content."""
    intent_file = tmp_path / "intent.yml"
    intent_file.write_text(_VALID_INTENT)
    out_dir = tmp_path / "out"
    out_dir.mkdir()

    # First, write the file via bare generate so committed == rendered
    write_result = runner.invoke(
        app,
        ["generate", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert write_result.exit_code == 0, f"Setup write failed: {write_result.stdout}"

    # Now --check must confirm no drift
    check_result = runner.invoke(
        app,
        ["generate", "--check", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert check_result.exit_code == 0, (
        f"Expected exit 0 (in sync), got {check_result.exit_code}: {check_result.stdout}"
    )


def test_generate_check_exits_1_on_drift(tmp_path: Path) -> None:
    """generate --check exits 1 when committed file is stale (drift detected)."""
    intent_file = tmp_path / "intent.yml"
    intent_file.write_text(_VALID_INTENT)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    (out_dir / "cross-seed").mkdir()
    (out_dir / "cross-seed" / "config.js").write_text("stale content")

    result = runner.invoke(
        app,
        ["generate", "--check", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert result.exit_code == 1, (
        f"Expected exit 1 (drift), got {result.exit_code}: {result.stdout}"
    )


_VALID_INTENT_WITH_QBM = """\
tools:
  cross_seed: null
  qbit_manage:
    qbt_host: "http://qbittorrent.selfhost.svc.cluster.local:8080"
    tracker_tags:
      - keyword: "beyond-hd"
        tag: "beyond-hd"
    share_limits:
      - name: "group-beyond-hd"
        tracker_tag: "beyond-hd"
        max_ratio: 3.0
        priority: 1
    recyclebin_days: 30
    rem_orphaned: false
    rem_unregistered: false
sagas: []
"""


def test_generate_writes_qbit_manage_config_yml(tmp_path: Path) -> None:
    """generate with qbit_manage block writes qbit_manage/config.yml, exits 0."""
    intent_file = tmp_path / "intent.yml"
    intent_file.write_text(_VALID_INTENT_WITH_QBM)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    # qbit_manage cat: is sourced from the co-located arrconf.yml categories.
    shutil.copy(_ARRCONF_YML, out_dir / "arrconf.yml")
    result = runner.invoke(
        app,
        ["generate", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert result.exit_code == 0, f"Expected exit 0, got {result.exit_code}: {result.stdout}"
    config_yml = out_dir / "qbit_manage" / "config.yml"
    assert config_yml.exists(), "qbit_manage/config.yml was not written"
    content = config_yml.read_text(encoding="utf-8")
    assert "# GENERATED by 'arrconf generate'" in content
    assert "cat_update: false" in content
    # cat is now POPULATED from arrconf.yml categories (qbit_manage rejects empty cat).
    assert "cat: {}" not in content
    assert "/data/torrents/" in content


def test_generate_check_exits_1_when_file_absent(tmp_path: Path) -> None:
    """generate --check exits 1 when committed file does not yet exist."""
    intent_file = tmp_path / "intent.yml"
    intent_file.write_text(_VALID_INTENT)
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    # Explicitly do NOT create cross-seed/config.js

    result = runner.invoke(
        app,
        ["generate", "--check", "--intent", str(intent_file), "--output-dir", str(out_dir)],
    )
    assert result.exit_code == 1, (
        f"Expected exit 1 (drift / absent file), got {result.exit_code}: {result.stdout}"
    )
