"""Unit tests for arrconf.generators.intent (Phase 28 INTENT-02/XSEED-02).

No HTTP — generator is pure Python.
"""

from __future__ import annotations

import json
import re

from arrconf.generators.intent import generate_cross_seed
from arrconf.intent_config import CrossSeedConfig


def test_generate_cross_seed_minimal() -> None:
    """Header present, module.exports structure valid, ends with semi+newline."""
    cfg = CrossSeedConfig(torznab=["http://prowlarr.test/1/api?apikey=${PROWLARR_API_KEY}"])
    result = generate_cross_seed(cfg)
    assert result.startswith("// GENERATED by 'arrconf generate'")
    assert "module.exports = " in result
    assert result.endswith(";\n")


def test_generate_cross_seed_deterministic() -> None:
    """Two calls with identical config produce byte-identical strings."""
    cfg = CrossSeedConfig(torznab=["http://a"], torrent_clients=["qbittorrent:http://b"])
    assert generate_cross_seed(cfg) == generate_cross_seed(cfg)


def test_generate_cross_seed_sort_keys() -> None:
    """Keys in JS output must be sorted for byte-stable idempotence."""
    cfg = CrossSeedConfig(torznab=["http://a"], action="inject", link_type="hardlink")
    output = generate_cross_seed(cfg)
    body = re.search(r"module\.exports = (\{.*\});", output, re.DOTALL)
    assert body is not None
    data = json.loads(body.group(1))
    keys = list(data.keys())
    assert keys == sorted(keys), f"Keys not sorted: {keys}"


def test_generate_cross_seed_omits_empty() -> None:
    """Empty list fields are omitted; linkType/action always present."""
    cfg = CrossSeedConfig()
    result = generate_cross_seed(cfg)
    body = re.search(r"module\.exports = (\{.*\});", result, re.DOTALL)
    assert body is not None
    data = json.loads(body.group(1))
    assert "torznab" not in data
    assert "torrentClients" not in data
    assert "linkDirs" not in data
    assert "linkType" in data
    assert "action" in data


def test_generate_cross_seed_camelcase() -> None:
    """torrent_clients renders as torrentClients; link_dirs as linkDirs in the JS output."""
    cfg = CrossSeedConfig(
        torrent_clients=["qbittorrent:http://user:pass@host:8080"],
        link_dirs=["/data/media"],
    )
    result = generate_cross_seed(cfg)
    body = re.search(r"module\.exports = (\{.*\});", result, re.DOTALL)
    assert body is not None
    data = json.loads(body.group(1))
    assert "torrentClients" in data
    assert "linkDirs" in data
    assert "torrent_clients" not in data
    assert "link_dirs" not in data


def test_generate_cross_seed_data_based_fields() -> None:
    """data_dirs/search_cadence/skip_recheck/max_data_depth render in camelCase."""
    cfg = CrossSeedConfig(
        torznab=["http://a"],
        data_dirs=["/media/films", "/media/series"],
        search_cadence="1day",
        skip_recheck=False,
        max_data_depth=3,
    )
    result = generate_cross_seed(cfg)
    body = re.search(r"module\.exports = (\{.*\});", result, re.DOTALL)
    assert body is not None
    data = json.loads(body.group(1))
    assert data["dataDirs"] == ["/media/films", "/media/series"]
    assert data["searchCadence"] == "1day"
    assert data["skipRecheck"] is False
    assert data["maxDataDepth"] == 3
    # snake_case keys never leak
    assert "data_dirs" not in data
    assert "search_cadence" not in data


def test_generate_cross_seed_data_fields_omitted_when_unset() -> None:
    """Unset data-based fields are omitted (unset ≠ default)."""
    cfg = CrossSeedConfig(torznab=["http://a"])
    data = json.loads(
        re.search(r"module\.exports = (\{.*\});", generate_cross_seed(cfg), re.DOTALL).group(1)
    )
    assert "dataDirs" not in data
    assert "searchCadence" not in data
    assert "skipRecheck" not in data
    assert "maxDataDepth" not in data
