"""Unit tests for generate_qbit_manage() (Phase 31 QBM-01/QBM-02).

No HTTP — generator is pure Python.
"""

from __future__ import annotations

import io

from ruyaml import YAML

from arrconf.generators.intent import generate_qbit_manage
from arrconf.intent_config import QbitManageConfig, ShareLimitGroup
from arrconf.resources.qbittorrent.category import Category as QbitCategory

_yaml_safe = YAML(typ="safe")


def _cats() -> list[QbitCategory]:
    """Two arrconf categories mirroring generate_qbit_categories output."""
    return [
        QbitCategory(name="films", savePath="/data/torrents/films"),
        QbitCategory(name="anime-zoe", savePath="/data/torrents/anime-zoe"),
    ]


def test_generate_qbit_manage_minimal() -> None:
    """Header present, output non-empty."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert result.startswith(
        "# GENERATED by 'arrconf generate' from intent.yml — DO NOT EDIT BY HAND"
    )
    assert len(result) > 0


def test_generate_qbit_manage_deterministic() -> None:
    """Two calls with identical config produce byte-identical strings."""
    cfg = QbitManageConfig()
    assert generate_qbit_manage(cfg, _cats()) == generate_qbit_manage(cfg, _cats())


def test_generate_qbit_manage_priority_order() -> None:
    """ShareLimitGroups are emitted sorted by priority ascending."""
    cfg = QbitManageConfig(
        share_limits=[
            ShareLimitGroup(name="high-prio", tracker_tag="tracker-a", priority=5),
            ShareLimitGroup(name="low-prio", tracker_tag="tracker-b", priority=1),
        ]
    )
    result = generate_qbit_manage(cfg, _cats())
    pos_low = result.index("low-prio:")
    pos_high = result.index("high-prio:")
    assert pos_low < pos_high, "priority=1 group must appear before priority=5 group"


def test_generate_qbit_manage_env_tags_literal() -> None:
    """!ENV tags emitted as literal unquoted YAML (Pitfall 1)."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "  user: !ENV QBT_USER" in result
    assert "  pass: !ENV QBT_PASS" in result
    # Must NOT be quoted variants
    assert "user: '!ENV QBT_USER'" not in result
    assert 'user: "!ENV QBT_USER"' not in result
    assert "pass: '!ENV QBT_PASS'" not in result
    assert 'pass: "!ENV QBT_PASS"' not in result


def test_generate_qbit_manage_cat_update_false() -> None:
    """cat_update: false in commands (QBM-02), cat_update: true never present."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "cat_update: false" in result
    assert "cat_update: true" not in result


def test_generate_qbit_manage_commands_section() -> None:
    """commands: section drives operations; share_limits on, cat_update off."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert result.index("commands:") < result.index("qbt:")
    assert "  share_limits: true" in result


def test_generate_qbit_manage_tracker_section_name() -> None:
    """The mandatory section key is `tracker:`, NOT `tracker_tags:`."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "\ntracker:\n" in result
    assert "tracker_tags:" not in result


def test_generate_qbit_manage_directory_root_dir() -> None:
    """directory.root_dir is mandatory (qbit_manage errors without it)."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "\ndirectory:\n" in result
    assert "  root_dir: /data/torrents" in result


def test_generate_qbit_manage_recyclebin_top_level() -> None:
    """recyclebin is a top-level section (not nested under settings)."""
    result = generate_qbit_manage(QbitManageConfig(recyclebin_days=30), _cats())
    assert "\nrecyclebin:\n" in result
    assert "  empty_after_x_days: 30" in result


def test_generate_qbit_manage_cat_populated() -> None:
    """cat section lists every category as <name>: <save_path> (NOT empty — qbit_manage
    rejects an empty cat section). cat_update:false above is the no-writer guard."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "cat: {}" not in result
    assert "  films: /data/torrents/films" in result
    assert "  anime-zoe: /data/torrents/anime-zoe" in result


def test_generate_qbit_manage_cat_sorted() -> None:
    """Categories emitted sorted by name for determinism."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert result.index("anime-zoe:") < result.index("films:")


def test_generate_qbit_manage_rem_orphaned_default_false() -> None:
    """Default config emits rem_orphaned: false (D-04 opt-in)."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    assert "rem_orphaned: false" in result


def test_generate_qbit_manage_rem_orphaned_opt_in() -> None:
    """rem_orphaned: true when explicitly set in config."""
    result = generate_qbit_manage(QbitManageConfig(rem_orphaned=True), _cats())
    assert "rem_orphaned: true" in result


def test_generate_qbit_manage_recyclebin_days() -> None:
    """empty_after_x_days reflects recyclebin_days from config."""
    result = generate_qbit_manage(QbitManageConfig(recyclebin_days=7), _cats())
    assert "empty_after_x_days: 7" in result


def test_generate_qbit_manage_yaml_valid() -> None:
    """Non-qbt sections parse as valid YAML; cat_update is False (in commands) and
    cat is populated."""
    result = generate_qbit_manage(QbitManageConfig(), _cats())
    # The qbt: block carries !ENV tags that yaml.safe_load cannot parse — strip it.
    kept = [
        line
        for line in result.splitlines()
        if "!ENV" not in line and line.strip() not in ("qbt:",) and not line.startswith("  host:")
    ]
    parsed = _yaml_safe.load(io.StringIO("\n".join(kept)))
    assert parsed["commands"]["cat_update"] is False
    assert parsed["commands"]["share_limits"] is True
    assert parsed["cat"] == {
        "films": "/data/torrents/films",
        "anime-zoe": "/data/torrents/anime-zoe",
    }
    assert parsed["recyclebin"]["enabled"] is True
